- hosts: aly 
  roles:
    - common
    - docker-shadowsocks
    - docker-shadowsocks_client
    - docker-reg
- hosts: vps
  roles:
    - common
    - docker-shadowsocks
    - docker-nginx
    - 
      role: softasap.sa-vpn-softether
      softether_vpn_users:
        - 
          name: test
          password: test
      softether_ipsec_presharedkey: Abcd123456
