---
- name: reload unit
  become: true
  command: systemctl daemon-reload
#  when: "facter_os.release.major == 7"
  when: "ansible_distribution_major_version == 7"

- name: restart docker
  service:
    name: docker
    state: restarted
