---

- name: get docker images
  shell: "docker images --filter=reference='{{imageName}}:{{imageTag}}' --format='{%raw%}{{.Repository}}:{{.Tag}}{%endraw%}' "
  register: images

- name: pull image
  shell: "docker pull {{imageName}}:{{imageTag}}"
  when: images.stdout.find(imageName)
  
- name: do debug
  debug:
    msg: 
      - "docker params:"
      - "  image={{imageName}}:{{imageTag}}"
      - "  command={{command}}"
      - "  serviceName={{serviceName}}"
      - "  tcp={{tcp}}"
      - "  udp={{udp}}"
      - "  volumns={{volumns}}"
   
- name: install docker service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker-{{serviceName}}.service
  notify:
    - reload docker service
    - enable docker service
    - stop docker service

- name: start docker service
  shell: echo "just for trigger handler"
  notify:
    - start docker service