---

- name: get docker images
  shell: "docker images --filter=reference='{{imageName}}:{{imageTag}}' --format='{%raw%}{{.Repository}}:{{.Tag}}{%endraw%}' "
  register: images

- name: pull image
  shell: "docker pull {{imageName}}:{{imageTag}}"
  when: images.stdout.find(imageName)
  
   
- name: check docker service 
  shell: "systemctl is-active docker-{{serviceName}}.service"
  register: service_state
  ignore_errors: true
    
- name: install docker service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker-{{serviceName}}.service
  when: (service_state.stdout == 'unknown') or
        (service_state.stdout == 'failed')
