---

#- name: get docker images
#  shell: "docker images --filter=reference='{{imageName}}:{{imageTag}}' --format='{%raw%}{{.Repository}}:{{.Tag}}{%endraw%}' "
#  register: images

- name: pull image
  shell: "docker pull {{imageName}}:{{imageTag}}"
#  when: images.stdout.find(imageName) == -1
  
- name: install docker service
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker-{{serviceName}}.service
  register: instate
  

- name: reload docker service
  shell: systemctl daemon-reload
  when: instate.changed
  
- name: get docker service state
  shell: systemctl is-active docker-{{serviceName}}
  register: svcstate
  ignore_errors: yes

- name: restart docker service
  shell: systemctl restart docker-{{serviceName}}
  when: (instate.changed) or 
        (svcstate.stdout.find("active") == -1)