---
# tasks file for docker-reg

- name: install docker registry
  include_role:
    name: docker-service
    vars:
      imageName: imageName
      imageTag: imageTag
      serviceName: serviceName
      command: command
      tcp: tcp
      udp: udp
      volumns: volumns