---
- name: override default vars if running under client mode
  include_vars: defaults/client.yml
  when: workmode=="client"

- name: install shadowsocks
  include_role:
    name: docker-service
    vars:
      imageName: imageName
      imageTag: imageTag
      serviceName: serviceName
      command: command
      tcp: tcp
      udp: udp
      volumns: volumns