---
- include: "os/{{ ansible_os_family }}.yml"

- name: bind-utils
  package: 
    name: bind-utils
    state: latest

- name: telnet
  package:
    name: telnet
    state: latest

- name: git
  package:
    name: git
    state: latest

- name: wget
  package:
    name: wget
    state: latest

- name: speed-cli
  pip: 
    name: speedtest-cli
