---
- include: "os/{{ ansible_os_family }}.yml"

- name: speed-cli
  pip: 
    name: speedtest-cli

- name: packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - bind-utils
    - telnet
    - git
    - wget
    - nc
    - lrzsz

- include: "os/docker/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
